[package]
name = "backend-process"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[dependencies]
firmware-api = { path = "../firmware-api" }
hidapi = "2.6.3"
rusqlite = { version = "0.37.0", features = ["bundled"] }

[lints]
workspace = true
